services:
  front:
    build: ./tanticampus
    container_name: tanticampus_front
    ports:
      - "3030:80"
    depends_on:
      - api
    restart: always

  api:
    build: ./server
    container_name: tanticampus_api
    ports:
      - "8030:8030"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tanticampus25
      - DB_USER=tanticampus_user
      - DB_PASSWORD=1234
      - JWT_SECRET=supersecretkey
      - PORT=8030
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.4
    container_name: tanticampus_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tanticampus25
      MYSQL_USER: tanticampus_user
      MYSQL_PASSWORD: 1234
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  db_data:
